name: Generate Website Demo WebP
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate-webp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Website to WebP
        uses: danielpos178/website-to-gif@main
        with:
          url: "https://ctrl-alt-truth.vercel.app/"
          file_format: "WebP"
          file_name: "demo"
          no_scroll: true
          time_per_frame: 50
          time_between_frames: 50
          number_of_frames: 100

      - name: Commit file to GH repo
        run: |
          git config --global user.name "website-to-gif[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add demo.webp
          git commit -m "Update website demo WebP" || echo "No changes to commit"
          git push
